In [226]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
import tensorflow
import deepcut
from pythainlp.corpus import stopwords
import re
import matplotlib.pyplot as plt

In [200]:
myData=[]
i=1
filename = "./dataset/forCLFnohash1label1000.csv"

In [201]:
def tokenizer(tweet):
    #global i
    #i = i+1
    #if i%100 == 0: print("%d from %d" (i,len(myData)))
    pattern = re.compile(r"[^\u0E00-\u0E4C]|^'|'$|''|\u0E46|\u0E3F")
    char_to_remove = re.findall(pattern, tweet)
    list_with_char_removed = [char for char in tweet if not char in char_to_remove]
    result_string = ''.join(list_with_char_removed)
    return deepcut.tokenize(result_string)

In [202]:
import csv
with open(filename, 'r', encoding='utf8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        myData.append(row["tweet"])

In [203]:
df = pd.read_csv(filename)
y = np.array(df['label'])
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [204]:
v = TfidfVectorizer(tokenizer=tokenizer, stop_words=stopwords.words('thai'))
train_data_feature = v.fit_transform(myData).toarray()
print(train_data_feature)
#tokenizer("ไม่รู้เหมือนกัน")

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [205]:
vocab = v.get_feature_names()
#print(vocab)

In [206]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
X, y = train_data_feature, y
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X,y).predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3,

In [227]:
X_train, X_test, y_train, y_test = train_test_split(train_data_feature, y, test_size=0.2, random_state=0)
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
clf.score(X_test, y_test)

0.27000000000000002

In [233]:
x1,y1 = clf

TypeError: 'OneVsRestClassifier' object is not iterable

In [209]:
predict = clf.predict(X_test)
for i in range(len(predict)):
    print(X_test[i],predict[i])

[ 0.  0.  0. ...,  0.  0.  0.] 2
[ 0.  0.  0. ...,  0.  0.  0.] 7
[ 0.  0.  0. ...,  0.  0.  0.] 7
[ 0.  0.  0. ...,  0.  0.  0.] 5
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 6
[ 0.  0.  0. ...,  0.  0.  0.] 7
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 4
[ 0.  0.  0. ...,  0.  0.  0.] 2
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 7
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 5
[ 0.  0.  0. ...,  0.  0.  0.] 4
[ 0.  0.  0. ...,  0.  0.  0.] 2
[ 0.  0.  0. ...,  0.  0.  0.] 4
[ 0.  0.  0. ...,  0.  0.  0.] 3
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 6
[ 0.  0.  0. ...,  0.  0.  0.] 4
[ 0.  0.  0. ...,  0.  0.  0.] 3
[ 0.  0.  0. ...,  0.  0.  0.] 8
[ 0.  0.  0. ...,  0.  0.  0.] 7
[ 0.  0.  0. ...,  0.  0.  0.] 6
[ 0.  0.  0. ...,  0.  0.  0.] 5
[ 0.  0.  0. ...,  0.  0.  0.] 1
[ 0.  0.  0. ...,  0.  0.  0.] 2
[ 0.  0.  0. ...,  0.  0.  0.] 4
[ 0.  0.  

In [210]:
from gensim.models import Word2Vec
lw = [list(tokenizer(i)) for i in myData]
print(lw)

[['เด็ก', 'เก่ง', 'มี', 'ความ', 'สามารถ', 'แต่', 'ค่าย', 'ไม่', 'โปรโมต', 'มัน', 'ก็', 'เหมือน', 'หัว', 'ล้าน', 'ได้', 'หวีไก่', 'ได้', 'พลอย', 'วานร', 'ได้แก้ว', 'ตา', 'บอด', 'ได้แว่น', 'แหม่', 'มมมม', 'ไม่', 'รู้', 'จะ', 'เอา', 'สำนวน', 'ไทย', 'ไหน', 'มาพู'], ['จอด', 'รถ', 'แบบ', 'นี้', 'ใคร', 'จะ', 'ออก', 'ได้', 'แค่', 'ยก', 'ขา', 'ตั้ง', 'ขึ้น', 'ยัง', 'ไม่', 'ได้', 'เลย', 'คน', 'เค้า', 'มี', 'ธุระ', 'ต้อง', 'ใช้', 'มอไซต์', 'ไม่', 'นึก', 'ถึงใจ', 'คน', 'อื่น', 'มั้ง', 'เลย', 'หรือ', 'ยัง', 'ไง', 'ความ', 'เกรงใจ', 'มี', 'มั้ง', 'ไห'], ['สติ', 'ไม่', 'มี', 'แล้ว', 'ตอน', 'นี้'], ['เชี่ย', 'เอ้ย', 'ดู', 'ตาราง', 'เรียน', 'ไม่ได'], ['สัก', 'หน่อย', 'จะ', 'เลิก', 'เล่น', 'เฟ'], ['มัน', 'น่า', 'โมโห', 'นิด', 'นึง', 'นะ', 'รู้', 'ว่า', 'เรื่อง', 'ของ', 'ทาน', 'บ่น', 'มาก', 'ไม่', 'ดี', 'แต่', 'เคย', 'ม่ะ', 'ไอ้', 'ที่', 'เก็บ', 'ไว้', 'อยาก', 'ทาน', 'คน', 'เดียว', 'ไม่', 'อยาก', 'แบ่ง', 'ใคร', 'แต่', 'โดน', 'คน', 'อื่น', 'ทาน', 'ไป', 'จน', 'หมด', 'ไม่', 'เหลืออ่'], ['อาจ', 'ดู', 'เหมือน'

In [211]:
vector = Word2Vec(lw,min_count=10)
print(vector)

Word2Vec(vocab=212, size=100, alpha=0.025)


In [212]:
vector.wv.similar_by_word("ดี")

[('ไม่', 0.9997943043708801),
 ('ว่า', 0.9997918605804443),
 ('อยู่', 0.9997870922088623),
 ('จะ', 0.9997856616973877),
 ('ก็', 0.9997825622558594),
 ('มา', 0.999779999256134),
 ('ที่', 0.9997707605361938),
 ('ไป', 0.9997682571411133),
 ('ต้อง', 0.9997663497924805),
 ('เธอ', 0.9997644424438477)]

In [213]:
vector.wv.similar_by_word("ไม่")

[('มา', 0.9998967051506042),
 ('จะ', 0.9998863935470581),
 ('ที่', 0.9998847246170044),
 ('ก็', 0.9998777508735657),
 ('ไป', 0.9998699426651001),
 ('ให้', 0.9998672008514404),
 ('ต้อง', 0.9998670220375061),
 ('มี', 0.9998626112937927),
 ('ตัว', 0.9998571276664734),
 ('ได้', 0.9998559951782227)]

In [214]:
import gensim
model = gensim.models.Word2Vec(lw, size=100)
w2v = dict(zip(model.wv.index2word, model.wv.syn0))

In [215]:
class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        self.dim = len(list(word2vec.values()).next())

    def fit(self, X, y):
        return self

    def transform(self, X):
        return np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec]
                    or [np.zeros(self.dim)], axis=0)
            for words in X
        ])
    

In [216]:
class TfidfEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        self.word2weight = None
        self.dim = len(word2vec.values().next())

    def fit(self, X, y):
        tfidf = TfidfVectorizer(analyzer=lambda x: x)
        tfidf.fit(X)
        # if a word was never seen - it must be at least as infrequent
        # as any of the known words - so the default idf is the max of 
        # known idf's
        max_idf = max(tfidf.idf_)
        self.word2weight = defaultdict(
            lambda: max_idf,
            [(w, tfidf.idf_[i]) for w, i in tfidf.vocabulary_.items()])

        return self

    def transform(self, X):
        return np.array([
                np.mean([self.word2vec[w] * self.word2weight[w]
                         for w in words if w in self.word2vec] or
                        [np.zeros(self.dim)], axis=0)
                for words in X
            ])

In [217]:
def vectorize_feature(sentence):
    s_vector = np.zeros(100)
    for word in sentence:
        if word in model.wv.vocab:
            s_vector = s_vector + model.wv.__getitem__(word)
    return s_vector
print(lw[1])
vectorize_feature(lw[1])

['จอด', 'รถ', 'แบบ', 'นี้', 'ใคร', 'จะ', 'ออก', 'ได้', 'แค่', 'ยก', 'ขา', 'ตั้ง', 'ขึ้น', 'ยัง', 'ไม่', 'ได้', 'เลย', 'คน', 'เค้า', 'มี', 'ธุระ', 'ต้อง', 'ใช้', 'มอไซต์', 'ไม่', 'นึก', 'ถึงใจ', 'คน', 'อื่น', 'มั้ง', 'เลย', 'หรือ', 'ยัง', 'ไง', 'ความ', 'เกรงใจ', 'มี', 'มั้ง', 'ไห']


array([  7.81175638,   2.4415479 ,  -0.56259473,  -4.02280677,
        -3.86915523,  -5.7707581 ,  -3.45090508,  -5.77281135,
         3.68998216,  14.84857889,  -4.89030018,   2.41266308,
         5.6533301 ,  -1.21887831,   2.39247107,   0.83476517,
        -3.05166988,  -2.02377545,   0.86844327,   3.76467882,
         1.10817436,  -4.7752923 ,  -2.21082096,   1.77021613,
        -2.31732023,   2.11677404,   3.34363409,  -0.77444471,
         3.58481374,   1.49463989,   1.60712286,   8.64888653,
         8.97909634,   3.15572707,   1.88795081,  -4.22719769,
         5.58243242,   4.55971079,   8.18847325,  -1.88499584,
        -4.89250225,   4.51818676,   3.20737867,  -2.15557036,
         2.69908375,   7.3238649 ,   6.61120405,   4.15691087,
        -0.49478432,  13.08050809,   4.91882287,   1.90201578,
        -1.82808889,  -4.68846328,   7.61741538,   4.7762164 ,
        -5.51828231,  -5.76418982,  -0.8052751 ,  -0.74522271,
        -8.14399904,  -0.75270128,   4.01479753,   2.44

In [218]:
'กลัว' in model.wv.vocab

True

In [219]:
def extract_feature(list_of_sentences):
    f_vector = []
    for sentence in list_of_sentences:
        f_vector.append(vectorize_feature(sentence))
    return f_vector

In [220]:
X = extract_feature(lw)

In [221]:
print(X[0],X[1])

[ 4.95670452  1.5738982  -0.36521688 -2.57776316 -2.45653506 -3.65803975
 -2.22472862 -3.65623266  2.34128609  9.46313361 -3.12816727  1.54241629
  3.60104115 -0.76253762  1.525904    0.52809433 -1.93228224 -1.28962518
  0.55101872  2.40026262  0.68431905 -3.02427137 -1.3929074   1.10146596
 -1.46508062  1.3212642   2.13150518 -0.47866586  2.2566321   0.97093599
  0.99996152  5.49894249  5.74245707  2.0047986   1.2067547  -2.69142971
  3.53508684  2.92902566  5.22593464 -1.18919079 -3.14222455  2.88481246
  2.03396239 -1.36374833  1.72739036  4.67129472  4.19216275  2.63536622
 -0.32991491  8.31195794  3.13639814  1.20736701 -1.18703617 -2.98190466
  4.84889152  3.04860373 -3.5238453  -3.65942563 -0.51221637 -0.5109832
 -5.18839924 -0.4730328   2.55707238  1.53973129  4.08631595  1.31871174
 -8.01728415 -2.23746165 -6.50887315 -1.85758475  4.21348925 -3.9460864
 -4.62452341  5.15207483  9.10822371  6.16074063 -0.34620546 -8.2632784
  4.44574303  5.2474751   4.44727034 -4.5310828   2.34

In [222]:
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X,y).predict(X)

array([6, 6, 5, 7, 7, 6, 1, 7, 6, 6, 7, 7, 6, 5, 7, 1, 1, 6, 7, 1, 1, 1, 1,
       1, 6, 1, 7, 1, 1, 7, 7, 1, 1, 6, 1, 7, 6, 7, 7, 8, 1, 6, 1, 7, 8, 2,
       1, 7, 8, 8, 7, 1, 3, 1, 5, 7, 8, 7, 5, 1, 7, 6, 7, 7, 7, 7, 7, 3, 4,
       1, 5, 8, 1, 3, 1, 6, 1, 1, 7, 7, 1, 8, 1, 1, 1, 1, 6, 5, 5, 3, 1, 1,
       5, 7, 3, 7, 7, 7, 1, 1, 5, 7, 1, 3, 8, 7, 6, 7, 7, 7, 5, 5, 7, 7, 8,
       8, 1, 1, 6, 3, 7, 5, 6, 8, 1, 7, 5, 5, 2, 7, 7, 6, 3, 1, 3, 8, 2, 4,
       8, 7, 7, 2, 5, 5, 7, 7, 5, 2, 7, 7, 2, 1, 7, 6, 1, 7, 8, 7, 8, 2, 1,
       7, 8, 7, 7, 3, 7, 2, 7, 8, 7, 2, 5, 2, 8, 2, 7, 2, 7, 7, 2, 8, 5, 2,
       2, 2, 7, 5, 7, 6, 3, 7, 7, 5, 5, 5, 2, 5, 6, 3, 6, 7, 8, 3, 7, 8, 6,
       2, 8, 8, 1, 7, 3, 7, 5, 5, 7, 2, 6, 8, 7, 1, 8, 7, 5, 2, 7, 6, 7, 2,
       5, 7, 8, 7, 6, 3, 5, 7, 8, 2, 5, 5, 7, 2, 2, 6, 7, 7, 7, 7, 3, 7, 7,
       7, 3, 7, 2, 8, 3, 7, 7, 6, 7, 7, 6, 5, 3, 7, 7, 1, 7, 7, 5, 7, 7, 7,
       3, 6, 7, 3, 5, 3, 3, 7, 6, 6, 3, 3, 6, 7, 7, 7, 8, 5, 1, 3, 7, 7, 7,
       3, 3,

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
clf.score(X_test, y_test)

0.22

In [224]:
clf.predict([vectorize_feature(tokenizer('ง่วงนอนจังเลย'))])

array([7])

In [225]:
clf.predict([vectorize_feature(tokenizer('นี่ให้ผีตัวไหนมาพูดก็ได้ก็กลายเป็นข่าวได้แล้วหรอ แล้วยังมีคนหน้าโง่เชื่อแบบจริงๆจังๆโดยไม่พรูฟห่าอะไรเลย แล้วก็มาว่าร้ายใส่เข'))])

array([4])