In [621]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
import tensorflow
import deepcut
from pythainlp.corpus import stopwords
from pythainlp.tokenize import word_tokenize
from pythainlp.spell.pn import correction
from pythainlp.spell import *
import re
import matplotlib.pyplot as plt
from sklearn.metrics import recall_score, precision_score, f1_score

In [622]:
myData=[]
i=1
filename = "./dataset/forCLFnohash1000.csv"

In [623]:
## This is a function that receives tweet in string sentence and remove
## non Thai characters and also punctuations. Then it tokenizes the
## sentence into words with "Deepcut"

def tokenizer(tweet):
    #global i
    #i = i+1
    #if i%100 == 0: print("%d from %d" (i,len(myData)))
    pattern = re.compile(r"[^\u0E00-\u0E4C]|^'|'$|''|\u0E46|\u0E3F")
    char_to_remove = re.findall(pattern, tweet)
    list_with_char_removed = [char for char in tweet if not char in char_to_remove]
    result_string = ''.join(list_with_char_removed)
    #return deepcut.tokenize(result_string)
    return word_tokenize(result_string, engine='deepcut')

In [624]:
## Read and make a list of tweets from a given file to be used for
## scikit-learn TfIdf

import csv
with open(filename, 'r', encoding='utf8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        myData.append(row["tweet"])

In [625]:
## Read a file and make a numpy array of labels

df = pd.read_csv(filename)
#y = np.array(df['label'])
#print(y)

y1 = np.array(df['anger'])
y2 = np.array(df['anticipation'])
y3 = np.array(df['disgust'])
y4 = np.array(df['fear'])
y5 = np.array(df['joy'])
y6 = np.array(df['sadness'])
y7 = np.array(df['surprise'])
y8 = np.array(df['trust'])


In [626]:
## Extract features from a tweet with TfIdf

v = TfidfVectorizer(tokenizer=tokenizer, stop_words=stopwords.words('thai'))
#v = CountVectorizer(tokenizer=tokenizer, stop_words=stopwords.words('thai'))
train_data_feature = v.fit_transform(myData).toarray()
print(train_data_feature)
#tokenizer("ไม่รู้เหมือนกัน")

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [627]:
vocab = v.get_feature_names()
print(len(vocab))
for voc in range(len(vocab)):
    i=0
    for doc in train_data_feature:
        if doc[voc]>0:
            i = i+1
    if i>1: print(vocab[voc],i)

2424
ก 2
กก 2
กด 2
กระดาษ 2
กระทืบ 2
กระเป๋า 4
กรี๊ด 2
กลัว 14
กลาง 2
กลาย 2
กล้า 7
กว่ 6
กะ 4
กั 7
กาก 2
การ์ตูน 2
กิน 10
กีฬา 2
กี่ 5
กี้ 7
กุ 6
กูรัก 2
กูสวย 2
กูอี 3
กูเกลียด 2
ก่อ 4
ก้ 6
ก้อ 4
ขนาด 13
ขยัน 2
ขอบคุณ 4
ขอบเขต 2
ขับ 2
ขาย 3
ขี้ 3
ขึ้ 2
ขโมย 3
ข่าว 4
ข้อ 3
ข้าว 2
ค 2
คณะ 2
คน 148
คบ 6
ครอบครัว 4
ครั 4
ครั้ 2
ครึ่ง 3
ครู 4
ความหมาย 2
ควาย 3
คอน 2
คอย 4
คัน 2
คัม 2
คาด 2
คาบ 2
คืน 10
คุณค่า 2
คุย 23
คุ้ม 2
คู่ 6
ค่ 6
ค่า 9
ค้าง 2
ฆ่า 3
งั้น 3
งาน 17
งี้ 6
ง่วง 2
จบ 13
จอง 3
จิก 2
จิง 2
จิต 2
จีน 2
จุด 5
จ่า 3
ชอบ 23
ชัดเจน 2
ชั้น 6
ชาติ 3
ชาย 10
ชีวิต 13
ชื่อ 11
ช่อง 2
ช่าง 4
ซัก 9
ซิ 2
ซื้อ 6
ซ่อม 3
ซ้อม 2
ซ้ำ 2
ดด 2
ดราม่า 2
ดัน 2
ดิ 2
ดี 63
ดีใจ 3
ดึง 2
ดู 27
ด่า 6
ด้ว 6
ตก 10
ตกลง 2
ตกอ่ 2
ตบ 5
ตรวจ 2
ตลก 2
ตอ 2
ตอน 40
ตอบ 9
ตัง 4
ตัด 3
ตัดสินใจ 3
ตัดใจ 2
ตัว 57
ตา 11
ตาย 18
ติด 8
ติดต่อ 2
ติ่ง 2
ตี 4
ตีน 2
ตื่น 8
ตื่นเต้น 3
ตุ๊กตา 2
ต้น 4
ต้องการ 5
ถล่ม 2
ถาม 6
ถีบ 2
ถ่าย 4
ท 2
ทน 4
ทราบ 3
ทรู 2
ทวิต 6
ทัก 4
ทำ 82
ทำร้าย 4
ทำใจ 4
ทำไ 3
ทิ้ง 7
ท่า 2
ท่าน 3
น 14
นอน 

In [628]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
#X, y = train_data_feature, y
X = train_data_feature

n=1000
k=5
e=8
emo = n/e
chunck = emo/k
data = []
for i in range(k):
    data.append(        
        {
        "train":{"X":[],"y1":[],"y2":[],"y3":[],"y4":[],
                  "y5":[],"y6":[],"y7":[],"y8":[]},
        "test":{"X":[],"y1":[],"y2":[],"y3":[],"y4":[],
                  "y5":[],"y6":[],"y7":[],"y8":[]}
        })
for i in range(1000):
    for m in range(5):
        if m*chunck <= i%emo < (m+1)*chunck: 
            data[m]["test"]["X"].append(X[i])
            data[m]["test"]["y1"].append(y1[i])
            data[m]["test"]["y2"].append(y2[i])
            data[m]["test"]["y3"].append(y3[i])
            data[m]["test"]["y4"].append(y4[i])
            data[m]["test"]["y5"].append(y5[i])
            data[m]["test"]["y6"].append(y6[i])
            data[m]["test"]["y7"].append(y7[i])
            data[m]["test"]["y8"].append(y8[i])
        else: 
            data[m]["train"]["X"].append(X[i])
            data[m]["train"]["y1"].append(y1[i])
            data[m]["train"]["y2"].append(y2[i])
            data[m]["train"]["y3"].append(y3[i])
            data[m]["train"]["y4"].append(y4[i])
            data[m]["train"]["y5"].append(y5[i])
            data[m]["train"]["y6"].append(y6[i])
            data[m]["train"]["y7"].append(y7[i])
            data[m]["train"]["y8"].append(y8[i])
##print(data)
    

#clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X,y)
#clf.score(X,y)
#clf = OneVsRestClassifier(LinearSVC(random_state=0))
#clf = svm.SVC(decision_function_shape='ovr')
#scores = cross_val_score(clf,X,y,cv=5)
#print(scores,scores.mean())

#clf1 = svm.SVC().fit(X1_train,y1_train)
#clf1.score(X1_test,y1_test)



In [629]:
#clf1k0 anger 0-fold
print(len(data[0]["test"]["X"]))
print(len(data[0]["test"]["y1"]))
clf1k0 = svm.LinearSVC().fit(data[0]["train"]["X"],data[0]["train"]["y1"])
clf1k0.score(data[0]["test"]["X"],data[0]["test"]["y1"])

200
200


0.87

In [630]:
#X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=0)
#clf1no = svm.LinearSVC().fit(X_train,y_train)
#clf1no.score(X_test,y_test)
k=1
clf1k1 = svm.LinearSVC().fit(data[k]["train"]["X"],data[k]["train"]["y1"])
clf1k1.score(data[k]["test"]["X"],data[k]["test"]["y1"])

0.88

In [631]:
#clf1k2 anger 2-fold
k=2
clf1k2 = svm.LinearSVC().fit(data[k]["train"]["X"],data[k]["train"]["y1"])
clf1k2.score(data[k]["test"]["X"],data[k]["test"]["y1"])

0.88500000000000001

In [632]:
#clf1k3 anger 3-fold
k=3
clf1k3 = svm.LinearSVC().fit(data[k]["train"]["X"],data[k]["train"]["y1"])
clf1k3.score(data[k]["test"]["X"],data[k]["test"]["y1"])
clf1k3.predict(data[k]["test"]["X"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [633]:
#clf1k4 anger 4-fold
k=4
clf1k4 = svm.LinearSVC().fit(data[k]["train"]["X"],data[k]["train"]["y1"])
clf1k4.score(data[k]["test"]["X"],data[k]["test"]["y1"])
clf1k4.predict(data[k]["test"]["X"])

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [634]:
#clf2k0 anticipation 0-fold
k=0
clf2k0 = svm.LinearSVC().fit(data[k]["train"]["X"],data[k]["train"]["y2"])
clf2k0.score(data[k]["test"]["X"],data[k]["test"]["y2"])

0.86499999999999999

In [635]:
print(clf2k0.predict(data[k]["test"]["X"]),data[k]["test"]["y2"])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [636]:
print(clf1k0.predict(data[k]["test"]["X"]),data[k]["test"]["y1"])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [638]:
s_emo = []
d_emo = []
x_emo = []
for i in range(1000):
    x_emo.append([i])
    #if int(i/25)%2==0: x_emo.append([0])
    #else: x_emo.append([1])
    if i<125: 
        s_emo.append(1)
        d_emo.append(0)
    else:
        s_emo.append(0)
        d_emo.append(1)

from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)
skf.get_n_splits(X[:200], y1[:200])
for train_index, test_index in skf.split(X[:200], y1[:200]):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y1[train_index], y1[test_index]
    tclf = svm.LinearSVC().fit(X_train,y_train)
    predict = tclf.predict(X_test)
    
    print(tclf.predict(X_test))
    print(y_test)
    print(recall_score(y_test,predict),precision_score(y_test,predict),f1_score(y_test,predict))
    


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
0.88 0.628571428571 0.733333333333
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0
 1 1 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
0.96 0.685714285714 0.8
[1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1
 1 0 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
0.92 0.71875 0.80701754386
[1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
0.88 0.628571428571 0.733333333333
[1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1
 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
0.88 0.666666666667 0.758620689655


In [451]:
clf = OneVsRestClassifier(LinearSVC(random_state=0))
scores = cross_val_score(clf,X,y,cv=5)
print(scores, scores.mean())

ValueError: Found input variables with inconsistent numbers of samples: [1000, 4000]

In [411]:
clf2 = svm.SVC().fit(X2_train,y2_train)
clf2.score(X2_test,y2_test)
clf2.predict(X1_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [552]:
from gensim.models import Word2Vec
lw = [list(tokenizer(i)) for i in myData]
print(lw)

[['นอก', 'จาก', 'จะ', 'คัน', 'ปาก', 'อยาก', 'เม้าท์', 'แล้ว', 'ยัง', 'คัน', 'ไม้', 'คัน', 'มือ', 'รวม', 'ถึง', 'คัน', 'ตีน', 'อยาก', 'กระทืบ', 'คน', 'ด้วย'], ['ดูแบง', 'ไม่', 'ได'], ['รภ', 'แม่ง', 'ติด', 'ไร', 'ว่ะ'], ['ซัก', 'วัน', 'บ้าน', 'จะ', 'แตก', 'เพราะ', 'ปากแม่', 'นั่น', 'แหล'], ['ซัมซุง', 'ไม่', 'มี', 'ช่อง', 'ห้อง', 'กุ๊งกิ๊งหรอย้'], ['สลัด', 'มา', 'กกกกกกจิก', 'ได้', 'จิก', 'ดี', 'หึยยย'], ['กาก', 'ที่สุด', 'อยู่', 'ที่', 'เน็ต', 'ทรู', 'ที่', 'ประมูล', 'คลื่น', 'ความ', 'ถี่', 'มา', 'เยอะ', 'ไม่', 'ได้', 'ช่วย', 'อะไร', 'เลย', 'ที', 'หลัง', 'ไม่', 'ต้อง', 'ไป', 'ประมูล', 'มา', 'ให้', 'เสีย', 'ตัง', 'หรอก', 'เอา', 'เงิน', 'มา', 'พัฒนา', 'ระบบ', 'ดี', 'กว่'], ['โอ้ยแม่ง', 'อย่า', 'ให้', 'กู', 'ใช้', 'สันดาร', 'นะ', 'ละมึง', 'จะ', 'รู้จัก', 'ตัว', 'กู', 'ที่', 'แท้จริง', 'กู', 'ไม่', 'ใช่', 'คน', 'ตลก', 'อย่าง', 'ที่', 'มึง', 'เห็น'], ['อีนุบน', 'ถึง', 'พยาบาล', 'ส่วน', 'ตัว', 'ให้', 'ฟัง', 'อีก', 'แล้'], ['ขัดใจ', 'พี่เค้า', 'ได้', 'ไง', 'ยุ'], ['เพื่อน', 'ลืม', 'นั'], ['เขา'

In [553]:
vector = Word2Vec(lw,min_count=10)
print(vector)

Word2Vec(vocab=204, size=100, alpha=0.025)


In [554]:
vector.wv.similar_by_word("ดี")

[('ไม่', 0.9998248815536499),
 ('ก็', 0.9998147487640381),
 ('จะ', 0.9998117089271545),
 ('มา', 0.9998067617416382),
 ('ที่', 0.9998047947883606),
 ('ว่า', 0.9998012781143188),
 ('ไป', 0.9997918605804443),
 ('คน', 0.9997912049293518),
 ('มี', 0.9997866153717041),
 ('เรา', 0.9997848272323608)]

In [555]:
vector.wv.similar_by_word("ไม่")

[('มา', 0.9998780488967896),
 ('ที่', 0.9998747110366821),
 ('ก็', 0.9998695850372314),
 ('จะ', 0.9998680353164673),
 ('ทำ', 0.9998543858528137),
 ('เรา', 0.9998505115509033),
 ('ให้', 0.9998494982719421),
 ('ไป', 0.9998489022254944),
 ('นี้', 0.9998478293418884),
 ('ความ', 0.9998399019241333)]

In [ ]:
import gensim
model = gensim.models.Word2Vec(lw, size=100)
w2v = dict(zip(model.wv.index2word, model.wv.syn0))

In [ ]:
class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        self.dim = len(list(word2vec.values()).next())

    def fit(self, X, y):
        return self

    def transform(self, X):
        return np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec]
                    or [np.zeros(self.dim)], axis=0)
            for words in X
        ])
    

In [ ]:
class TfidfEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        self.word2weight = None
        self.dim = len(word2vec.values().next())

    def fit(self, X, y):
        tfidf = TfidfVectorizer(analyzer=lambda x: x)
        tfidf.fit(X)
        # if a word was never seen - it must be at least as infrequent
        # as any of the known words - so the default idf is the max of 
        # known idf's
        max_idf = max(tfidf.idf_)
        self.word2weight = defaultdict(
            lambda: max_idf,
            [(w, tfidf.idf_[i]) for w, i in tfidf.vocabulary_.items()])

        return self

    def transform(self, X):
        return np.array([
                np.mean([self.word2vec[w] * self.word2weight[w]
                         for w in words if w in self.word2vec] or
                        [np.zeros(self.dim)], axis=0)
                for words in X
            ])

In [575]:
def vectorize_feature(sentence):
    s_vector = np.zeros(100)
    for word in sentence:
        if word in model.wv.vocab:
            s_vector = s_vector + model.wv.__getitem__(word)
    return s_vector
print(lw[1])
vectorize_feature(lw[0])

['ดูแบง', 'ไม่', 'ได']


array([ 2.62344056,  0.82879071, -0.18836974, -1.35079373, -1.30303023,
       -1.93736044, -1.17065206, -1.95728113,  1.25010194,  4.99919701,
       -1.65554061,  0.82043897,  1.90727219, -0.40231132,  0.8041875 ,
        0.26820879, -1.03477995, -0.66449516,  0.28415216,  1.2781313 ,
        0.40486092, -1.59707244, -0.74396669,  0.59177294, -0.79076634,
        0.71224293,  1.13383931, -0.25754069,  1.21327968,  0.51457775,
        0.54317006,  2.88054352,  3.03743833,  1.0419967 ,  0.64747681,
       -1.44583651,  1.88147802,  1.54069765,  2.75443998, -0.6289988 ,
       -1.6608537 ,  1.51671315,  1.08191276, -0.72519112,  0.90799106,
        2.46803536,  2.23163044,  1.40560104, -0.16049199,  4.39576329,
        1.66282056,  0.6171304 , -0.62398137, -1.57482931,  2.55379307,
        1.61318017, -1.85336779, -1.94563256, -0.26885089, -0.24088036,
       -2.73074698, -0.25515043,  1.34840968,  0.81908446,  2.17022705,
        0.68680402, -4.23168437, -1.15468807, -3.44165678, -0.98

In [ ]:
'กลัว' in model.wv.vocab

In [576]:
def extract_feature(list_of_sentences):
    f_vector = []
    for sentence in list_of_sentences:
        f_vector.append(vectorize_feature(sentence))
    return np.array(f_vector)

In [577]:
X = extract_feature(lw)

In [578]:
print(X[0],X[1])

[ 2.62344056  0.82879071 -0.18836974 -1.35079373 -1.30303023 -1.93736044
 -1.17065206 -1.95728113  1.25010194  4.99919701 -1.65554061  0.82043897
  1.90727219 -0.40231132  0.8041875   0.26820879 -1.03477995 -0.66449516
  0.28415216  1.2781313   0.40486092 -1.59707244 -0.74396669  0.59177294
 -0.79076634  0.71224293  1.13383931 -0.25754069  1.21327968  0.51457775
  0.54317006  2.88054352  3.03743833  1.0419967   0.64747681 -1.44583651
  1.88147802  1.54069765  2.75443998 -0.6289988  -1.6608537   1.51671315
  1.08191276 -0.72519112  0.90799106  2.46803536  2.23163044  1.40560104
 -0.16049199  4.39576329  1.66282056  0.6171304  -0.62398137 -1.57482931
  2.55379307  1.61318017 -1.85336779 -1.94563256 -0.26885089 -0.24088036
 -2.73074698 -0.25515043  1.34840968  0.81908446  2.17022705  0.68680402
 -4.23168437 -1.15468807 -3.44165678 -0.98801418  2.24275918 -2.08585365
 -2.44657392  2.7275008   4.81929048  3.27652663 -0.18174266 -4.37149331
  2.37592676  2.73763403  2.34035524 -2.42228319  1

In [ ]:
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X,y).predict(X)

In [597]:
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=0)
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
print(clf.predict(X_test), y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [ ]:
clf.predict([vectorize_feature(tokenizer('ง่วงนอนจังเลย'))])

In [ ]:
clf.predict([vectorize_feature(tokenizer('นี่ให้ผีตัวไหนมาพูดก็ได้ก็กลายเป็นข่าวได้แล้วหรอ แล้วยังมีคนหน้าโง่เชื่อแบบจริงๆจังๆโดยไม่พรูฟห่าอะไรเลย แล้วก็มาว่าร้ายใส่เข'))])

In [610]:
skf = StratifiedKFold(n_splits=10)
skf.get_n_splits(X[:250], y1[:250])
for train_index, test_index in skf.split(X[:250], y1[:250]):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y1[train_index], y1[test_index]
    tclf = svm.LinearSVC().fit(X_train,y_train)
    print(tclf.predict(X_test))
    print(tclf.score(X_test,y_test))
print(tclf.predict([vectorize_feature(tokenizer('ง่วงนอนจังเลย'))]))
print(tclf.predict([vectorize_feature(tokenizer('นี่ให้ผีตัวไหนมาพูดก็ได้ก็กลายเป็นข่าวได้แล้วหรอ แล้วยังมีคนหน้าโง่เชื่อแบบจริงๆจังๆโดยไม่พรูฟห่าอะไรเลย แล้วก็มาว่าร้ายใส่เข'))]))

TRAIN: [ 13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30
  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66
  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102
 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
 121 122 123 124 138 139 140 141 142 143 144 145 146 147 148 149 150 151
 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187
 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241
 242 243 244 245 246 247 248 249] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12 125 126 127 128 129
 130

[1 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0]
0.666666666667
TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173
 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191
 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209
 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 238 239
 240 241 242 243 244 245 246 247 248 249] TEST: [101

In [594]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf.get_n_splits(X)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y1[train_index], y1[test_index]
    tclf = svm.SVC().fit(X_train,y_train)
    print(tclf.predict(X_test),y_test)
    print(tclf.score(X_test,y_test))

TRAIN: [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444

ValueError: The number of classes has to be greater than one; got 1

In [563]:
print(skf)

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)
